#!/usr/bin/env python3
"""
Writes the board configuration reference out of the declaration.

Input:  scripts/config/schema.py's BOARD_SCHEMA — the table the generator walks.
Output: configs/BOARD_CONFIG_REFERENCE.md — one section per table, one row per
        field: what it accepts, whether it is required, and the macro or cmake
        variable it becomes.

The reference is generated so it cannot describe a field the generator does not
carry, or miss one it does: scripts/test/test_board_config.py regenerates it and
compares. CONFIGURATION.md stays the guide — what a board author writes, why —
and points here for the field list.

Usage: python3 scripts/config/gen_board_doc.py [--out FILE]
"""

import argparse
import os
import pathlib
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from config import BOARD_SCHEMA, engine  # noqa: E402

HEADER = """# Board Configuration Reference

<!-- Generated by scripts/config/gen_board_doc.py from scripts/config/schema.py.
     Do not edit: run the generator. CONFIGURATION.md is the guide. -->

Every field a `BoardConfig.toml` may carry, the values it is accepted under and
what each becomes. `scripts/test/test_board_config.py` regenerates this file and
holds the generator's output to the golden headers under
`scripts/test/board_config/`, so a field cannot reach the firmware without a row
here.

"""


def accepted(field) -> str:
    """What a field's values are held to."""
    kind = type(field).__name__
    if kind == "Text":
        return "a string"
    if kind == "Word":
        return "letters, digits and underscores"
    if kind == "Int":
        if getattr(field, "high", None) is None:
            return f"an integer, {field.low} or more"
        return f"an integer, {field.low} to {field.high}"
    if kind == "Bool":
        return "`true` or `false`"
    if kind == "Pin":
        return "a pin, `P<port><n>` (`PA0`–`PI15`)"
    if kind == "PinArray":
        return "a list of 1 to 8 pins"
    if kind == "Presence":
        return f"the board's own: a table named `{field.sub}`"
    if isinstance(field, engine.Named):
        values = ", ".join(f"`{v}`" for v in sorted(field.table))
        return f"one of: {values}"
    summary = getattr(field, "summary", None)
    if summary:
        return summary
    if isinstance(field, engine.Custom):
        checks = getattr(field, "checks", None)
        return f"`{checks.__name__}` holds it" if checks else "a value of its own"
    return "—"


def becomes(field, table) -> str:
    """What a field is written as."""
    if getattr(field, "include", False):
        return "the header the file opens with"
    if getattr(field, "cmake", None):
        return f"`{field.cmake}` in `board_config.cmake`"
    prefix = getattr(field, "prefix", "")
    macro = getattr(field, "macro", None)
    if macro:
        return f"`{macro}`"
    if prefix:
        return f"`{prefix}<value>`"
    for key in ("line", "index_macro"):
        held = getattr(field, key, None)
        if held:
            return f"`{held}` and the rows beside it"
    if isinstance(field, engine.Custom):
        lines = getattr(field, "lines", None)
        if lines is None:
            return "a macro of its own"
        return f"`{lines.__name__}`'s lines"
    return "—"


def sections() -> list[str]:
    out = [HEADER]
    for table in BOARD_SCHEMA:
        where = ".".join(table.path)
        out.append(f"## `[{where}]`" + (" — required" if table.required else ""))
        out.append("")
        if table.kind == engine.MAP:
            out.append(f"One table per {table.what}, the name of which is what the")
            out.append("firmware looks its macros up by.")
            out.append("")
        if table.lines is not None:
            bus = getattr(table.lines, "name", None)
            who = f"the {bus} bus's" if bus else f"`{table.lines.__name__}`'s"
            out.append(f"Validation and the lines are {who}: the fields below are")
            out.append("held to the rules, not emitted one by one.")
            out.append("")

        rows = []
        for item in [*table.preamble, *table.items]:
            rows.extend(items_of(item, table, None))
        emit(rows, out)
    return out


def items_of(item, table, note: str | None) -> list[tuple]:
    """The rows one item of a table holds: a field, or a group's fields.

    `note` is what the group a row came from asks of the table, so a field that
    only applies in one state says which.
    """
    if isinstance(item, engine.Group):
        if item.value is engine.PRESENT:
            note = f"`{item.field}` is set"
        elif item.value is engine.ABSENT:
            note = f"`{item.field}` is not set"
        else:
            note = item.note or f"`{item.field}` is `{item.value}`"
        rows = []
        for held in item.items:
            rows.extend(items_of(held, table, note))
        return rows
    return [(item, table, note)]


def emit(rows: list[tuple], out: list[str]) -> None:
    if not rows:
        return
    out.append("| Field | Accepts | When | Required | Becomes |")
    out.append("|-------|---------|------|----------|---------|")
    for field, table, note in rows:
        name = field.name or "—"
        if table.kind == engine.MAP:
            name = f"<name>.{name}" if field.name else "<name>"
        required = "yes" if getattr(field, "required", False) else ""
        out.append(f"| `{name}` | {accepted(field)} | {note or ''} | {required} | "
                   f"{becomes(field, table)} |")
    out.append("")


def main() -> int:
    parser = argparse.ArgumentParser(description="Write the board reference")
    parser.add_argument("--out", default="configs/BOARD_CONFIG_REFERENCE.md")
    args = parser.parse_args()
    text = "\n".join(sections()) + "\n"
    pathlib.Path(args.out).write_text(text)
    print(f"wrote {args.out} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
