#!/bin/bash

# This file is a part of ThetaRush.
#
# ThetaRush is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ThetaRush is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.
#
# If not, see <https://www.gnu.org/licenses/>.

# -- Attention: This file is generated by Deepseek R1 --

# Purpose: Recursively format files with specified extensions while excluding directories
# Dependencies: fd (preferred) or find, and clang-format

# Default configurations
DEFAULT_EXTENSIONS=("c" "h")         # Default file extensions to format
EXCLUDE_DIRS=("lib")                # Default directories to exclude
CLANG_FORMAT_CONFIG=""               # Custom clang-format config file path
USE_FD=0                             # 0 = use find, 1 = use fd

# Display usage information
usage() {
  echo "Usage: $0 [options]"
  echo "Options:"
  echo "  -e <extensions>    File extensions to format (comma-separated, e.g., 'c,h,cpp'), default: 'c,h'"
  echo "  -E <exclude_dirs>  Directories to exclude (comma-separated, e.g., 'libs,build'), default: 'libs'"
  echo "  -c <config_file>   clang-format configuration file (e.g., .clang-format or predefined style)"
  echo "  -h                 Show this help message"
  exit 1
}

# Check required dependencies
check_dependency() {
  if ! command -v clang-format &> /dev/null; then
    echo "Error: 'clang-format' not found. Please install it."
    echo "Installation: https://clang.llvm.org/docs/ClangFormat.html"
    exit 1
  fi

  if command -v fd &> /dev/null; then
    USE_FD=1
    return
  fi

  if command -v find &> /dev/null; then
    USE_FD=0
    return
  fi

  echo "Error: Neither 'fd' nor 'find' found. Please install one of them."
  echo "Install fd: https://github.com/sharkdp/fd#installation"
  echo "find is usually pre-installed on Unix-like systems"
  exit 1
}

# Format files using fd
format_with_fd() {
  # Build fd extension arguments (-e c -e h ...)
  local extension_args=()
  for ext in "${DEFAULT_EXTENSIONS[@]}"; do
    extension_args+=("-e" "$ext")
  done

  # Build exclude directory arguments
  local exclude_args=()
  for dir in "${EXCLUDE_DIRS[@]}"; do
    exclude_args+=("--exclude" "$dir")
  done

  echo "Formatting with fd (extensions: ${DEFAULT_EXTENSIONS[*]}, excluded directories: ${EXCLUDE_DIRS[*]})..."
  fd "${extension_args[@]}" "${exclude_args[@]}" -t f --exec-batch clang-format "${clang_format_args[@]}" {}
}

# Format files using find
format_with_find() {
  # Build find command components
  local find_cmd=("find" ".")
  
  # Add exclusion arguments
  if [ ${#EXCLUDE_DIRS[@]} -gt 0 ]; then
    local exclude_part=("(")
    for ((i=0; i<${#EXCLUDE_DIRS[@]}; i++)); do
      if [ $i -gt 0 ]; then
        exclude_part+=("-o")
      fi
      exclude_part+=("-name" "${EXCLUDE_DIRS[$i]}")
    done
    exclude_part+=(")" "-prune" "-o")
    find_cmd+=("${exclude_part[@]}")
  fi

  # Add file type and extension filters
  find_cmd+=("-type" "f")
  
  if [ ${#DEFAULT_EXTENSIONS[@]} -gt 0 ]; then
    local ext_part=("(")
    for ((i=0; i<${#DEFAULT_EXTENSIONS[@]}; i++)); do
      if [ $i -gt 0 ]; then
        ext_part+=("-o")
      fi
      ext_part+=("-name" "*.${DEFAULT_EXTENSIONS[$i]}")
    done
    ext_part+=(")")
    find_cmd+=("${ext_part[@]}")
  fi

  # Add print and execute commands
  find_cmd+=("-print0")

  echo "Formatting with find (extensions: ${DEFAULT_EXTENSIONS[*]}, excluded directories: ${EXCLUDE_DIRS[*]})..."
  "${find_cmd[@]}" | xargs -0 clang-format "${clang_format_args[@]}"
}

# Main function
main() {
  check_dependency

  # Parse command-line options
  while getopts "e:E:c:h" opt; do
    case $opt in
      e) IFS=',' read -ra DEFAULT_EXTENSIONS <<< "$OPTARG" ;;
      E) IFS=',' read -ra EXCLUDE_DIRS <<< "$OPTARG" ;;
      c) CLANG_FORMAT_CONFIG="$OPTARG" ;;
      h) usage ;;
      *) usage ;;
    esac
  done

  # Build clang-format arguments
  local clang_format_args=("-i")
  if [[ -n $CLANG_FORMAT_CONFIG ]]; then
    clang_format_args+=("-style=file:$CLANG_FORMAT_CONFIG")
  fi

  # Execute formatting
  if [ $USE_FD -eq 1 ]; then
    format_with_fd
  else
    format_with_find
  fi
  
  echo "Formatting completed!"
}

main "$@"