/**
 * This file is a part of ThetaGP.
 *
 * ThetaGP is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General
 * Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * ThetaGP is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the
 * implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this program.
 *
 * If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

namespace ThetaGP::Gamepad::Enums {

enum class DpadDirection {
  None = 0,
  Up = 1,
  Down = 2,
  Left = 3,
  Right = 4,

  Count
};

enum class SOCDMode {
  UpPriority = 0,
  Neutral = 1,
  SecondInputPriority = 2,
  FirstInputPriority = 3,
  Bypass = 4,

  Count
};

enum class Hotkey {
  None = 0,
  DpadDigital = 1,
  DpadLeftAnalog = 2,
  DpadRightAnalog = 3,
  HomeButton = 4,
  CaptureButton = 5,
  InvertXAxis = 6,
  InvertYAxis = 7,
  Toggle4WayMode = 8,
  ToggleDDI4WayMode = 9,
  SOCDUpPriority = 10,
  SOCDNeutral = 11,
  SOCDLastInput = 12,
  SOCDFirstInput = 13,
  SOCDBypass = 14,
  LoadProfile1 = 15,
  LoadProfile2 = 16,
  LoadProfile3 = 17,
  LoadProfile4 = 18,
  LoadProfile5 = 19,
  LoadProfile6 = 20,
  LoadProfile7 = 21,
  LoadProfile8 = 22,
  ButtonL3 = 23,
  ButtonR3 = 24,
  ButtonTpad = 25,
  ButtonRebootDefault = 26,
  ButtonB1 = 27,
  ButtonB2 = 28,
  ButtonB3 = 29,
  ButtonB4 = 30,
  L1Button = 31,
  R1Button = 32,
  L2Button = 33,
  R2Button = 34,
  S1Button = 35,
  S2Button = 36,
  A1Button = 37,
  A2Button = 38,
  A3Button = 39,
  A4Button = 40,
  NextProfile = 41,
  PreviousProfile = 42,
  DpadUp = 43,
  DpadDown = 44,
  DpadLeft = 45,
  DpadRight = 46,
  SaveConfig = 47,
  MenuNavUp = 48,
  MenuNavDown = 49,
  MenuNavLeft = 50,
  MenuNavRight = 51,
  MenuNavSelect = 52,
  MenuNavBack = 53,
  MenuNavToggle = 54,
  LedsNone = 55,
  LedsAnimationUp = 56,
  LedsAnimationDown = 57,
  LedsParameterUp = 58,
  LedsPressParameterUp = 59,
  LedsPressParameterDown = 60,
  LedsParameterDown = 61,
  LedsBrightnessUp = 62,
  LedsBrightnessDown = 63,
  LedsFadeTimeUp = 64,
  LedsFadeTimeDown = 65,
  AmbientLightEffectsChange = 66,
  AmbientLightEffectsOnOff = 67,
  AmbientLightEffectsBrightnessUp = 68,
  AmbientLightEffectsBrightnessDown = 69,
  AmbientLightEffectsParameterUp = 70,
  AmbientLightEffectsParameterDown = 71,
  AmbientLightEffectsFrameSpeedUp = 72,
  AmbientLightEffectsFrameSpeedDown = 73,
  AmbientLightEffectsCustomLinkage = 74,
  Enable4WayMode = 75,
  Disable4WayMode = 76,
  TurboCountUp = 77,
  TurboCountDown = 78,
  FocusModeToggle = 79,
  LSUp = 80,
  LSDown = 81,
  LSLeft = 82,
  LSRight = 83,
  RSUp = 84,
  RSDown = 85,
  RSLeft = 86,
  RSRight = 87,

  Count
};

enum class KeyAction {
  None = 0,
  Reserved = 1,
  AssignedToAddon = 2,
  ButtonPressUp = 3,
  ButtonPressDown = 4,
  ButtonPressLeft = 5,
  ButtonPressRight = 6,
  ButtonPressB1 = 7,
  ButtonPressB2 = 8,
  ButtonPressB3 = 9,
  ButtonPressB4 = 10,
  ButtonPressL1 = 11,
  ButtonPressR1 = 12,
  ButtonPressL2 = 13,
  ButtonPressR2 = 14,
  ButtonPressS1 = 15,
  ButtonPressS2 = 16,
  ButtonPressA1 = 17,
  ButtonPressA2 = 18,
  ButtonPressL3 = 19,
  ButtonPressR3 = 20,
  ButtonPressFn = 21,
  ButtonPressDdiUp = 22,
  ButtonPressDdiDown = 23,
  ButtonPressDdiLeft = 24,
  ButtonPressDdiRight = 25,
  SustainDpModeDp = 26,
  SustainDpModeLs = 27,
  SustainDpModeRs = 28,
  SustainSocdModeUpPrio = 29,
  SustainSocdModeNeutral = 30,
  SustainSocdModeSecondWin = 31,
  SustainSocdModeFirstWin = 32,
  SustainSocdModeBypass = 33,
  ButtonPressTurbo = 34,
  ButtonPressMacro = 35,
  ButtonPressMacro1 = 36,
  ButtonPressMacro2 = 37,
  ButtonPressMacro3 = 38,
  ButtonPressMacro4 = 39,
  ButtonPressMacro5 = 40,
  ButtonPressMacro6 = 41,
  CustomButtonCombo = 42,
  ButtonPressA3 = 43,
  ButtonPressA4 = 44,
  ButtonPressE1 = 45,
  ButtonPressE2 = 46,
  ButtonPressE3 = 47,
  ButtonPressE4 = 48,
  ButtonPressE5 = 49,
  ButtonPressE6 = 50,
  ButtonPressE7 = 51,
  ButtonPressE8 = 52,
  ButtonPressE9 = 53,
  ButtonPressE10 = 54,
  ButtonPressE11 = 55,
  ButtonPressE12 = 56,
  DigitalDirectionUp = 57,
  DigitalDirectionDown = 58,
  DigitalDirectionLeft = 59,
  DigitalDirectionRight = 60,
  AnalogDirectionLsXNeg = 61,
  AnalogDirectionLsXPos = 62,
  AnalogDirectionLsYNeg = 63,
  AnalogDirectionLsYPos = 64,
  AnalogDirectionRsXNeg = 65,
  AnalogDirectionRsXPos = 66,
  AnalogDirectionRsYNeg = 67,
  AnalogDirectionRsYPos = 68,
  AnalogDirectionModLow = 69,
  AnalogDirectionModHigh = 70,
  ButtonPressInputReverse = 71,
  SustainFocusMode = 72,
  Sustain48WayMode = 73,
  MenuNavigationUp = 74,
  MenuNavigationDown = 75,
  MenuNavigationLeft = 76,
  MenuNavigationRight = 77,
  MenuNavigationSelect = 78,
  MenuNavigationBack = 79,
  MenuNavigationToggle = 80,
  ModeGuitarFretGreen = 81,
  ModeGuitarFretRed = 82,
  ModeGuitarFretYellow = 83,
  ModeGuitarFretBlue = 84,
  ModeGuitarFretOrange = 85,
  ModeGuitarFretSoloGreen = 86,
  ModeGuitarFretSoloRed = 87,
  ModeGuitarFretSoloYellow = 88,
  ModeGuitarFretSoloBlue = 89,
  ModeGuitarFretSoloOrange = 90,
  ModeGuitarWhammy = 91,
  ModeGuitarPickup = 92,
  ModeGuitarTilt = 93,
  ModeDrumRedDrumpad = 94,
  ModeDrumBlueDrumpad = 95,
  ModeDrumYellowDrumpad = 96,
  ModeDrumGreenDrumpad = 97,
  ModeDrumYellowCymbal = 98,
  ModeDrumBlueCymbal = 99,
  ModeDrumGreenCymbal = 100,
  ModeDrumKickPedalLeft = 101,
  ModeDrumKickPedalRight = 102,
  ModeHotasRudderLeft = 103,
  ModeHotasRudderRight = 104,
  ModeHotasThrottleForward = 105,
  ModeHotasThrottleReverse = 106,
  ModeHotasRockerLeft = 107,
  ModeHotasRockerRight = 108,
  ModeHotasPedalLeft = 109,
  ModeHotasPedalRight = 110,
  ModeHotasPedalRudderLeft = 111,
  ModeHotasPedalRudderRight = 112,
  ModeWheelSteeringLeft = 113,
  ModeWheelSteeringRight = 114,
  ModeWheelShifterGear1 = 115,
  ModeWheelShifterGear2 = 116,
  ModeWheelShifterGear3 = 117,
  ModeWheelShifterGear4 = 118,
  ModeWheelShifterGear5 = 119,
  ModeWheelShifterGear6 = 120,
  ModeWheelShifterGearR = 121,
  ModeWheelShifterGearN = 122,
  ModeWheelShifterGearUp = 123,
  ModeWheelShifterGearDown = 124,
  ModeWheelButtonPlus = 125,
  ModeWheelButtonMinus = 126,
  ModeWheelDialUp = 127,
  ModeWheelDialDown = 128,
  ModeWheelDialEnter = 129,
  ModeWheelPedalGas = 130,
  ModeWheelPedalBrake = 131,
  ModeWheelPedalClutch = 132,

  Count
};

} // namespace ThetaGP::Gamepad::Enums
