"""
gen_ts — protocol/types.ts, the frontend's interfaces.

"""
import sys
from pathlib import Path
from typing import List, Optional

from proto_gen.model import (
    TS_TYPE_MAP,
    envelope_json_keys,
    envelope_on_side,
    fail_uncovered_fields,
    field_coverage_errors,
    record_types,
    sanitize_cpp_comment,
    split_array_type,
    to_pascal,
)

# ═════════════════════════════════════════════════════════════════════════════
# TypeScript Generator
# ═════════════════════════════════════════════════════════════════════════════

# The response envelope is declared in protocol.toml ([envelope]) and read out of
# it by envelope_on_side(), so the request types and the response types of
# gen_rust and gen_ts write a message's leading keys from the source of truth
# instead of each carrying a literal copy of them — and so the `appears` column
# decides, per side, whether a key is required, optional or not written there.
# See validate_envelope() for what the declaration is held to.


def gen_ts(proto: dict, out: Optional[Path] = None) -> str:
    lines: List[str] = []
    types = proto.get("types", [])
    enums = proto.get("enums", [])
    commands = proto.get("commands", [])
    error_codes = proto.get("error_codes", {})
    # The reply's leading keys as gen_ts compares a declared field against them:
    # a field whose key the envelope already writes is left to the envelope.
    envelope_keys = envelope_json_keys(proto)
    # The declared record types, by name: a field whose type is one of these
    # (with or without the array suffix) is written as that interface, and a
    # field whose type is an array of one as an array of it.
    records = record_types(proto)

    def ts_field_type(declared: str) -> str:
        """A field's declared `type` → the TypeScript type it is written as."""
        element, is_array = split_array_type(declared)
        ts_type = element if element in records else TS_TYPE_MAP.get(element, "any")
        return f"{ts_type}[]" if is_array else ts_type

    def w(line: str = "") -> None:
        lines.append(line)

    # ── Header ──────────────────────────────────────────────────────────────
    w("// =============================================================================")
    w("// Auto-generated by scripts/gen_proto.py — DO NOT EDIT MANUALLY")
    w("// Source: protocol/protocol.toml")
    w(f"// Generated: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    w("// =============================================================================")
    w()

    # ── Error codes ──────────────────────────────────────────────────────────
    w("// ---------------------------------------------------------------------------")
    w("// Error Codes")
    w("// ---------------------------------------------------------------------------")
    w("export const enum ErrorCode {")
    for name, info in error_codes.items():
        w(f"  {name} = {info['code']},")
    w("}")
    w()

    # ── Enums ────────────────────────────────────────────────────────────────
    for enum_info in enums:
        name = enum_info["name"]
        desc = sanitize_cpp_comment(enum_info.get("description", ""))
        w(f"// {desc}")
        w(f"export const enum {name} {{")
        for val in enum_info["values"]:
            desc = sanitize_cpp_comment(val.get("description", ""))
            w(f"  // {desc}")
            w(f"  {val['name']} = {val['value']},")
        w("}")
        w()

    # ── Interfaces ───────────────────────────────────────────────────────────
    for t in types:
        name = t["name"]
        desc = sanitize_cpp_comment(t.get("description", ""))
        w(f"// {desc}")
        w(f"export interface {name} {{")
        # A field marked `omit_in_serialize` is not part of the shape that
        # travels. Built before the lines are written and compared against the
        # declared array, so a filter added here is reported.
        interface_fields = [f for f in t["fields"] if not f.get("omit_in_serialize")]
        fail_uncovered_fields(field_coverage_errors(
            f"type {name}", "interface", t["fields"],
            [f["name"] for f in interface_fields]))
        for f in interface_fields:
            ts_type = ts_field_type(f["type"])
            desc = sanitize_cpp_comment(f.get("description", ""))
            w(f"  // {desc}")
            w(f"  {f['json']}: {ts_type};")
        w("}")
        w()

    # ── Command request/response interfaces ─────────────────────────────────
    for cmd_info in commands:
        domain = cmd_info["domain"]
        name = cmd_info["name"]
        full_name = f"{domain}.{name}"
        desc = sanitize_cpp_comment(cmd_info.get("description", ""))

        # Request interface
        req = cmd_info.get("request", [])
        w(f"// {full_name} — Request ({desc})")
        if req:
            w(f"export interface {to_pascal(domain)}{to_pascal(name)}Request {{")
            # The request's leading keys come from [envelope]'s request side, not
            # from two lines written here — and a key of `appears.request =
            # "some"` would be written optional, the same rule the response
            # interface below applies to the reply side.
            for f in envelope_on_side(proto, "request"):
                optional = "" if f["required"] else "?"
                w(f"  {f['json']}{optional}: {TS_TYPE_MAP[f['type']]};")
            # Each declared request field becomes a property of the interface;
            # the list is built and compared before the lines are written, so a
            # filter added here is reported rather than leaving the binding short
            # an argument.
            request_fields = list(req)
            fail_uncovered_fields(field_coverage_errors(
                full_name, "request", req,
                [f["name"] for f in request_fields]))
            for f in request_fields:
                ts_type = ts_field_type(f["type"])
                optional = "" if f.get("required", False) else "?"
                w(f"  {f['json']}{optional}: {ts_type};")
            w("}")
        else:
            # A command with no request fields still has a request, and its
            # leading keys are the envelope's request side — the same source as
            # the interface above, so the inline shape cannot drift from it.
            head = " ".join(
                f"{f['json']}{'?' if not f['required'] else ''}: {TS_TYPE_MAP[f['type']]};"
                for f in envelope_on_side(proto, "request"))
            w(f"export type {to_pascal(domain)}{to_pascal(name)}Request = {{ {head} }};")
        w()

        # Response interface
        resp = cmd_info.get("response", [])
        if resp:
            w(f"export interface {to_pascal(domain)}{to_pascal(name)}Response {{")
            # The reply's leading keys, from [envelope]'s reply side: a key every
            # reply carries is written plain and one only some replies carry
            # optional (`cmd?`, `queued?` — the error replies carry `status`
            # alone of these).
            for f in envelope_on_side(proto, "reply"):
                optional = "" if f["required"] else "?"
                w(f"  {f['json']}{optional}: {TS_TYPE_MAP[f['type']]};")
            # A field whose key the envelope above writes is left to it; every
            # other declared field gets an optional line of its own. The list is
            # built before the lines are written, and what the interface carries
            # is taken from the two places it writes keys — so a field dropped
            # from the list is reported instead of being noticed in the output.
            # (validate_envelope() refuses such a declaration, so the first half
            # of the coverage input is empty in a protocol that generates.)
            fields = [f for f in resp if f["json"] not in envelope_keys]
            fail_uncovered_fields(field_coverage_errors(
                full_name, "response", resp,
                [f["name"] for f in resp if f["json"] in envelope_keys]
                + [f["name"] for f in fields]))
            for f in fields:
                ts_type = ts_field_type(f["type"])
                w(f"  {f['json']}?: {ts_type};")
            w("}")
        else:
            # Generic response with status/cmd/queued
            pass
        w()

    result = "\n".join(lines)

    if out:
        out.write_text(result)
        print(f"  [ts]  wrote {out}", file=sys.stderr)

    return result
