"""
gen_cpp — protocol/proto.h, the device's header-only C++ binding.

"""
import sys
from pathlib import Path
from typing import Dict, List, Optional

from proto_gen.model import (
    CPP_TYPE_MAP,
    fail_uncovered_fields,
    field_coverage_errors,
    record_array_element_types,
    sanitize_cpp_comment,
    to_pascal,
    values_struct_name,
)

# ═════════════════════════════════════════════════════════════════════════════
# C++ Generator
# ═════════════════════════════════════════════════════════════════════════════

def gen_cpp(proto: dict, out: Optional[Path] = None) -> str:
    lines: List[str] = []
    types = proto.get("types", [])
    enums = proto.get("enums", [])
    commands = proto.get("commands", [])
    error_codes = proto.get("error_codes", {})

    # Build type name → fields lookup for nested serialization
    type_fields: Dict[str, list] = {t["name"]: t["fields"] for t in types}
    type_namespaces: Dict[str, str] = {t["name"]: t.get("namespace", "") for t in types}
    # The record types a command field declares as an array of. They are not
    # binding types here: a reply carrying one is written by the function the
    # generator emits (protocol/proto_resp.h), which takes the record's declared
    # fields as a value struct of its own, so a struct with serialization
    # helpers beside it would be a second C++ projection of one declaration.
    record_arrays = record_array_element_types(proto)

    def w(line: str = "") -> None:
        lines.append(line)

    # ── Header ──────────────────────────────────────────────────────────────
    w("// =============================================================================")
    w("// Auto-generated by scripts/gen_proto.py — DO NOT EDIT MANUALLY")
    w("// Source: protocol/protocol.toml")
    w(f"// Generated: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    w("// =============================================================================")
    w("#pragma once")
    w("#include <cstdint>")
    w("#include <cstring>")

    w()

    # ── Error codes ──────────────────────────────────────────────────────────
    w("// =============================================================================")
    w("// Error Codes")
    w("// =============================================================================")
    class ProtoErrorCodeTag: pass  # marker for the class context

    # ── Enums ────────────────────────────────────────────────────────────────
    for enum_info in enums:
        name = enum_info["name"]
        w(f"// ---------------------------------------------------------------------------")
        w(f"// {name} — {sanitize_cpp_comment(enum_info.get('description', ''))}")
        w(f"// ---------------------------------------------------------------------------")
        w(f"enum class {name} : uint8_t {{")
        for val in enum_info["values"]:
            desc = sanitize_cpp_comment(val.get("description", ""))
            w(f"    {val['name']} = {val['value']}, // {desc}")
        w("};")
        w()
        w(f"inline const char *{name}Name({name} v) {{")
        w(f"    switch (v) {{")
        for val in enum_info["values"]:
            w(f"        case {name}::{val['name']}: return \"{val['name']}\";")
        w(f"        default: return \"UNKNOWN\";")
        w(f"    }}")
        w(f"}}")
        w()

    # ── Enum converters ──────────────────────────────────────────────────────

    # ── Struct definitions ───────────────────────────────────────────────────
    for t in types:
        name = t["name"]
        ns = t.get("namespace", "")
        desc = sanitize_cpp_comment(t.get("description", ""))
        if name in record_arrays:
            # No binding struct: the record is carried as a value struct of the
            # writer that writes a reply holding an array of it.
            w(f"// {name} — {desc}")
            w(f"// No struct here: {name} is a record type a command field")
            w(f"// declares as an array, so the reply carrying it is written by the")
            w(f"// function the generator emits. That function takes")
            w(f"// ThetaGP::Resp::{values_struct_name(name)}")
            w(f"// (protocol/proto_resp.h), which holds these declared fields and")
            w(f"// nothing else.")
            w()
            continue
        w(f"// ---------------------------------------------------------------------------")
        w(f"// {desc}")
        w(f"// ---------------------------------------------------------------------------")
        # Open namespace
        if ns:
            ns_parts = ns.split("::")
            for part in ns_parts:
                w(f"namespace {part} {{")
        w(f"struct {name} {{")
        # Every declared field is carried, and the list is built before the
        # lines are written so the coverage check reads the list this emitter
        # writes rather than a description of it.
        struct_fields = list(t["fields"])
        fail_uncovered_fields(field_coverage_errors(
            f"type {name}", "struct", t["fields"],
            [f["name"] for f in struct_fields]))
        for f in struct_fields:
            if f.get("omit_in_serialize"):
                # Still emit the field (used internally) but mark it
                pass
            cpp_type = CPP_TYPE_MAP.get(f["type"], f"/* unknown: {f['type']} */")
            desc = sanitize_cpp_comment(f.get("description", ""))
            default = ""
            if f["type"] in ("u8", "u16", "u32"):
                default_val = f.get("default", 0)
                if ns == "ThetaGP::Gamepad" and name == "GamepadRawInput":
                    mid_defaults = {"lx": "GAMEPAD_JOYSTICK_MID", "ly": "GAMEPAD_JOYSTICK_MID",
                                    "rx": "GAMEPAD_JOYSTICK_MID", "ry": "GAMEPAD_JOYSTICK_MID"}
                    if f["name"] in mid_defaults:
                        default = f"{{{mid_defaults[f['name']]}}}"
                    else:
                        default = f"{{{default_val}}}"
                else:
                    default = f"{{{default_val}}}"
            elif f["type"] == "bool":
                default = f"{{{str(f.get('default', 'false')).lower()}}}"
            elif f["type"] == "string":
                default = "{}"
            else:
                default = "{}"
            w(f"    {cpp_type} {f['name']}{default}; // {desc}")
        w("};")
        if ns:
            for _ in ns_parts:
                w("}")
        w()

    # Resolve fully-qualified C++ name for a type
    def fq_type_name(name: str, ns: str) -> str:
        if ns:
            return f"::{ns}::{name}"
        return name

    # ── Serialize helpers (accumulated into buffer, emitted inside class) ────
    _serialize_lines: List[str] = []

    def sw(line: str = "") -> None:
        _serialize_lines.append(line)

    for t in types:
        name = t["name"]
        ns = t.get("namespace", "")
        fq = fq_type_name(name, ns)
        desc = sanitize_cpp_comment(t.get("description", ""))
        if name in record_arrays:
            # No serialization helpers: the record type has no binding struct
            # above, and its own writer carries the keys (protocol/proto_resp.h).
            continue
        sw(f"    // Serialize {name} into a JsonObject")
        sw(f"    inline static void serialize{name}(JsonObject obj, const {fq} &v) {{")
        # A field is written unless protocol.toml says it is not part of the
        # serialized shape (`omit_in_serialize`) or gives it no key to be written
        # under (`json = ""`). Built before the writes and compared against the
        # declared array: a filter added here is a field the binding stops
        # carrying, which the check reports instead of leaving it silent.
        serialize_fields = [f for f in t["fields"]
                            if f["json"] and not f.get("omit_in_serialize")]
        fail_uncovered_fields(field_coverage_errors(
            f"type {name}", "serialize", t["fields"],
            [f["name"] for f in serialize_fields]))
        for f in serialize_fields:
            sw(f'        obj["{f["json"]}"] = v.{f["name"]};')
        sw("    }")
        sw()

        # Deserialize
        sw(f"    // Deserialize {name} from a JsonDocument")
        sw(f"    inline static void deserialize{name}(const JsonDocument &doc, {fq} &v) {{")
        # The same reading as the serialized shape and a list of its own: the two
        # loops are separate, so a filter that reaches only one of them is a
        # filter only one of the two checks can report.
        deserialize_fields = [f for f in t["fields"]
                              if f["json"] and not f.get("omit_in_serialize")]
        fail_uncovered_fields(field_coverage_errors(
            f"type {name}", "deserialize", t["fields"],
            [f["name"] for f in deserialize_fields]))
        for f in deserialize_fields:
            json_key = f["json"]
            field_name = f["name"]
            default_val = f.get("default", 0)
            if f["type"] == "string":
                sw(f'        v.{field_name} = doc["{json_key}"] | "";')
            elif f["type"] == "bool":
                sw(f'        v.{field_name} = doc["{json_key}"] | false;')
            else:
                sw(f'        v.{field_name} = doc["{json_key}"] | {default_val};')
        sw("    }")
        sw()

    # ── Proto class ──────────────────────────────────────────────────────────
    w("// =============================================================================")
    w("// Proto class — command dispatch + serialization")
    w("// =============================================================================")
    w("namespace ThetaGP {")
    w()
    # ErrorCode inside class
    w("class Proto {")
    w("public:")
    w("    // Error Codes")
    w("    enum class ErrorCode : uint8_t {")
    for name, info in error_codes.items():
        w(f"        {name} = {info['code']}, // {sanitize_cpp_comment(info['description'])}")
    w("    };")
    w()
    w("    // Command handler signature (new: uses our own Json class)")
    w("    using Handler = void (*)(const char *cmd, const Json &json);")
    w()
    w("    // ── Handler registration ──")
    for cmd_info in commands:
        domain = cmd_info["domain"]
        var_name = f"_{domain}{to_pascal(cmd_info['name'])}Handler"
        func_name = f"register{to_pascal(domain)}{to_pascal(cmd_info['name'])}"
        w(f"    inline static void {func_name}(Handler h) {{ {var_name} = h; }}")
    w()
    w("    // ── Dispatch ──")
    w("    inline static bool dispatch(const char *cmd, const Json &json) {")
    for i, cmd_info in enumerate(commands):
        domain = cmd_info["domain"]
        full_name = f"{domain}.{cmd_info['name']}"
        var_name = f"_{domain}{to_pascal(cmd_info['name'])}Handler"
        if i == 0:
            w(f'        if (strcmp(cmd, "{full_name}") == 0)              {{ if ({var_name}) {{ {var_name}(cmd, json); return true; }} }}')
        else:
            w(f'        else if (strcmp(cmd, "{full_name}") == 0) {{ if ({var_name}) {{ {var_name}(cmd, json); return true; }} }}')
    w("        return false;")
    w("    }")
    w()
    w("private:")
    for cmd_info in commands:
        domain = cmd_info["domain"]
        var_name = f"_{domain}{to_pascal(cmd_info['name'])}Handler"
        w(f"    inline static Handler {var_name} = nullptr;")
    w()
    w("}; // class Proto")
    w()
    w("} // namespace ThetaGP")
    w()
    w("#ifdef __GNUC__")
    w("#pragma GCC diagnostic push")
    w('#pragma GCC diagnostic ignored "-Wunused-parameter"')
    w("#endif")
    w()
    w("#ifdef __GNUC__")
    w("#pragma GCC diagnostic pop")
    w("#endif")
    w()

    result = "\n".join(lines)

    if out:
        out.write_text(result)
        print(f"  [cpp] wrote {out}", file=sys.stderr)

    return result
