"""
gen_resp — protocol/proto_resp.h, the response field tables as X-macros.

The firmware expands these to write a reply's payload, so the order, the JSON
keys and the printf conversions come from the declaration instead of from a
format string written by hand.

Moved out of scripts/gen_proto.py without a change to what it emits.
"""
import sys
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from proto_gen.model import (
    PRINTF_TYPE_MAP,
    ROLE_PRESENCE,
    hand_written_flag,
    optional_flag,
    sanitize_cpp_comment,
)

# ═════════════════════════════════════════════════════════════════════════════
# Response field table generator (C++ header, X-macro)
# ═════════════════════════════════════════════════════════════════════════════

def resp_macro(domain: str, name: str) -> str:
    """The name of the X-macro table of command <domain>.<name>."""
    return f"THETAGP_RESP_{domain.upper()}_{name.replace('-', '_').upper()}"


def gen_resp(proto: dict, out: Optional[Path] = None) -> str:
    """Response payload field tables, one X-macro per command, as C++.

    Each table lists the response fields of one command in the order
    protocol.toml declares them — the order the response writes them in — and
    each entry carries the JSON key, the printf argument type, the conversion
    for that type and the presence of the field. A consumer expands a table
    with a macro of its own, so the same list drives the bytes on the wire and
    anything that has to agree with them; the firmware's copy of the order, the
    keys and the specifiers is this file, not a format string written by hand.

    What the table cannot carry is the value of a field: that is firmware state,
    and it is what the consumer's macro supplies. It supplies it *by name* —
    X(<json name>, ...) selects the value for that name — so the two sides meet
    on the name and not on position, and a field added to or renamed in
    protocol.toml is a value the consumer does not have rather than a value
    printed under the wrong key.

    A field whose type has no printf form is a field no table can carry, and its
    response would come out short of it; commands with such a field get no table
    and are named in the header instead — beside the flag the field's
    `hand_written` declaration emits for the command, which the code that
    assembles that reply by hand asserts.
    """
    commands = proto.get("commands", [])
    lines: List[str] = []

    def w(line: str = "") -> None:
        lines.append(line)

    w("// =============================================================================")
    w("// Auto-generated by scripts/gen_proto.py — DO NOT EDIT MANUALLY")
    w("// Source: protocol/protocol.toml")
    w(f"// Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    w("// =============================================================================")
    w("#pragma once")
    w("#include <cstdint>")
    w()
    w("// Response payload fields of a command, in the order the response writes")
    w("// them, one table per command. A table is expanded with a macro of the")
    w("// consumer's own, called once per field as")
    w("//     X(<json name>, <printf argument type>, <conversion>, <presence>)")
    w("// where the name selects the value to write, the type is what that value")
    w("// has to be, the conversion is the printf specifier for it, and the")
    w("// presence is 1 or a flag that is 0 in a build without the field.")
    w("//")
    w("// A second flag, THETAGP_RESP_OPTIONAL_<command>_<field>, answers a")
    w("// different question about a field: whether a *reply* has to carry the")
    w("// key, which the presence above does not say. The field is in every")
    w("// build that writes it; what the flag carries is that the command's")
    w("// replies may leave the key out, and the write site names it, so a")
    w("// declaration that comes off the field stops that site from compiling.")
    w("//")
    w("// A third flag, THETAGP_RESP_HANDWRITTEN_<command>, says that the")
    w("// command gets no table at all: a response field of it is declared")
    w("// `hand_written` (protocol.toml), because its type has no printf form")
    w("// and a table would come out short of it. The reply is assembled by")
    w("// hand, and the code that assembles it names the flag, so a field whose")
    w("// marking comes off stops that reply from compiling.")
    w()

    # Presence flags, once per role a response field carries.
    roles = {f.get("role") for cmd in commands for f in cmd.get("response", [])}
    for role in sorted(r for r in roles if r in ROLE_PRESENCE):
        flag, guard = ROLE_PRESENCE[role]
        w(f"// role = \"{role}\": the field is written only in a build where")
        w(f"// {guard} is defined.")
        w(f"#ifdef {guard}")
        w(f"#define {flag} 1")
        w("#else")
        w(f"#define {flag} 0")
        w("#endif")
        w()

    # Presence flags, once per response field the TOML declares `optional`:
    # a reply of the command may leave the key out. Such a field still gets a
    # table entry below, with the constant presence 1 — whether a *build* writes
    # the field at all and whether a *reply* has to carry it are two questions,
    # and a presence column holds one answer, so the second question gets a flag
    # of its own instead of a second meaning for that column.
    #
    # The flag is the whole of what this emitter derives from the column, and it
    # is emitted so that the declaration travels to the code that has to keep it
    # true: the write site names the flag (src/test/config_cmd_handler.cpp for
    # config.save.dropped_keys), so a field whose `optional = true` comes off
    # stops that site from compiling rather than leaving a declaration no code
    # answers to. What the flag cannot carry is *when* the key is left out:
    # that rule has no column to be derived from and is written where the write
    # is (protocol.toml, [commands] config.save).
    optional_fields = [(cmd, f) for cmd in commands
                       for f in cmd.get("response", []) if f.get("optional")]
    for cmd, f in optional_fields:
        w(f"// {cmd['domain']}.{cmd['name']} declares {f['json']} "
          f"`optional = true` (protocol.toml):")
        w("// a reply of that command may leave the key out.")
        w(f"#define {optional_flag(cmd['domain'], cmd['name'], f['name'])} 1")
    if optional_fields:
        w()

    # Flags, once per command a response field declares `hand_written`: no
    # table can carry that field, so the command gets none and its reply is
    # assembled by hand at a site that names the flag. One flag per command and
    # not per field, because the reply is one piece of code: the marking says
    # which replies are written by hand, and the fields under it are the reason.
    hand_written = []
    for cmd in commands:
        marked = [f for f in cmd.get("response", []) if f.get("hand_written")]
        if marked:
            hand_written.append((cmd, marked))
    for cmd, marked in hand_written:
        w(f"// {cmd['domain']}.{cmd['name']} declares "
          f"{', '.join(f['json'] for f in marked)} `hand_written` (protocol.toml):")
        w("// no table carries a field of that type, so this command's reply is")
        w("// assembled by hand and the site that writes it names this flag.")
        w(f"#define {hand_written_flag(cmd['domain'], cmd['name'])} 1")
    if hand_written:
        w()

    unformattable: List[str] = []
    for cmd in commands:
        resp = cmd.get("response", [])
        if not resp:
            continue
        full_name = f"{cmd['domain']}.{cmd['name']}"
        missing = [f["name"] for f in resp if f["type"] not in PRINTF_TYPE_MAP]
        if missing:
            marked = any(f.get("hand_written") for f in resp
                         if f["type"] not in PRINTF_TYPE_MAP)
            flag = f" — written by hand, {hand_written_flag(cmd['domain'], cmd['name'])}" if marked else ""
            unformattable.append(f"{full_name} ({', '.join(missing)}){flag}")
            continue
        w(f"// {full_name} — {sanitize_cpp_comment(cmd.get('description', ''))}")
        w(f"#define {resp_macro(cmd['domain'], cmd['name'])}(X) \\")
        for i, f in enumerate(resp):
            ctype, spec = PRINTF_TYPE_MAP[f["type"]]
            flag = ROLE_PRESENCE.get(f.get("role"), ("1",))[0]
            continuation = " \\" if i + 1 < len(resp) else ""
            w(f'    X({f["name"]}, {ctype}, "{spec}", {flag}){continuation}')
        w()

    if unformattable:
        w("// No table, because a response field of no printf form would be missing")
        w("// from every response written through one. One whose such a field is")
        w("// declared `hand_written` names the flag the code that assembles that")
        w("// reply asserts (THETAGP_RESP_HANDWRITTEN_*, above):")
        for entry in unformattable:
            w(f"//   {entry}")
        w()

    result = "\n".join(lines) + "\n"

    if out:
        out.write_text(result)
        print(f"  [resp] wrote {out}", file=sys.stderr)

    return result
