"""
gen_rust — protocol/proto.rs, the Tauri backend's serde types.

Moved out of scripts/gen_proto.py without a change to what it emits.
"""
import sys
from pathlib import Path
from typing import List, Optional

from proto_gen.model import (
    RUST_TYPE_MAP,
    envelope_on_side,
    fail_uncovered_fields,
    field_coverage_errors,
    rust_ident,
    sanitize_cpp_comment,
    to_pascal,
    to_snake,
)

# ═════════════════════════════════════════════════════════════════════════════
# Rust Generator
# ═════════════════════════════════════════════════════════════════════════════

def gen_rust(proto: dict, out: Optional[Path] = None) -> str:
    lines: List[str] = []
    types = proto.get("types", [])
    enums = proto.get("enums", [])
    commands = proto.get("commands", [])
    error_codes = proto.get("error_codes", {})
    # A message's leading fields, as protocol.toml declares them, so this emitter
    # writes a request struct's and a response struct's first fields from the
    # source of truth — envelope_on_side() per side, called where each is
    # written.

    def w(line: str = "") -> None:
        lines.append(line)

    # ── Header ──────────────────────────────────────────────────────────────
    w("// =============================================================================")
    w("// Auto-generated by scripts/gen_proto.py — DO NOT EDIT MANUALLY")
    w("// Source: protocol/protocol.toml")
    w(f"// Generated: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    w("// =============================================================================")
    w()
    w("use serde::{Deserialize, Serialize};")
    w("use serde_json::Value;")
    w()

    # ── Error codes ──────────────────────────────────────────────────────────
    w("// ---------------------------------------------------------------------------")
    w("// Error Codes")
    w("// ---------------------------------------------------------------------------")
    w("#[derive(Debug, Clone, Copy, PartialEq, Eq)]")
    w("#[repr(u8)]")
    w("pub enum ErrorCode {")
    for name, info in error_codes.items():
        desc = sanitize_cpp_comment(info.get("description", ""))
        w(f"    /// {desc}")
        w(f"    {to_pascal(to_snake(name))} = {info['code']},")
    w("}")
    w()

    w("impl ErrorCode {")
    w("    pub fn from_u8(v: u8) -> Option<Self> {")
    w("        match v {")
    for name, info in error_codes.items():
        w(f"            {info['code']} => Some(Self::{to_pascal(to_snake(name))}),")
    w("            _ => None,")
    w("        }")
    w("    }")
    w("}")
    w()

    # ── Enums ────────────────────────────────────────────────────────────────
    for enum_info in enums:
        name = enum_info["name"]
        desc = sanitize_cpp_comment(enum_info.get("description", ""))
        w(f"/// {desc}")
        w("#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]")
        w("#[repr(u8)]")
        w(f"pub enum {name} {{")
        for val in enum_info["values"]:
            desc = sanitize_cpp_comment(val.get("description", ""))
            w(f"    /// {desc}")
            w(f"    #[serde(rename = \"{val['name'].lower()}\")]")
            w(f"    {to_pascal(val['name'].lower())} = {val['value']},")
        w("}")
        w()

    # ── Structs ──────────────────────────────────────────────────────────────
    for t in types:
        name = t["name"]
        desc = sanitize_cpp_comment(t.get("description", ""))
        w(f"/// {desc}")
        w("#[derive(Debug, Clone, Serialize, Deserialize)]")
        w(f"pub struct {name} {{")
        # Every declared field is carried, and the list is built before the lines
        # so the coverage check reads what this emitter writes.
        struct_fields = list(t["fields"])
        fail_uncovered_fields(field_coverage_errors(
            f"type {name}", "struct", t["fields"],
            [f["name"] for f in struct_fields]))
        for f in struct_fields:
            if f.get("omit_in_serialize"):
                rust_type = RUST_TYPE_MAP.get(f["type"], "Value")
            else:
                rust_type = RUST_TYPE_MAP.get(f["type"], "Value")
            desc = sanitize_cpp_comment(f.get("description", ""))
            serde_attr = f'#[serde(rename = "{f["json"]}")]'
            w(f"    /// {desc}")
            w(f"    {serde_attr}")
            w(f"    pub {rust_ident(f['name'])}: {rust_type},")
        w("}")
        w()

    # ── Command enum ─────────────────────────────────────────────────────────
    w("// ---------------------------------------------------------------------------")
    w("// Command types")
    w("// ---------------------------------------------------------------------------")
    w()

    # Generate request types for commands with request fields
    for cmd_info in commands:
        req = cmd_info.get("request", [])
        if not req:
            continue
        domain = cmd_info["domain"]
        name = cmd_info["name"]
        struct_name = f"{to_pascal(domain)}{to_pascal(name)}Request"
        w("#[derive(Debug, Clone, Serialize, Deserialize)]")
        w(f"pub struct {struct_name} {{")
        # A request carries the request side of [envelope] — the keys
        # protocol.toml declares as appearing in one — ahead of the fields the
        # command declares, so these lines come from that section like the
        # response struct's leading fields do, and the column decides their
        # optionality: a key of `appears.request = "always"` is required here,
        # one of `"some"` optional, and one of `"never"` is not written at all.
        for f in envelope_on_side(proto, "request"):
            t = RUST_TYPE_MAP[f["type"]]
            if f["required"]:
                w(f"    pub {rust_ident(f['name'])}: {t},")
            else:
                w(f"    pub {rust_ident(f['name'])}: Option<{t}>,")
        # Each declared request field becomes a field of the struct; the list is
        # built and compared before the lines are written, so a filter added here
        # is reported rather than leaving the binding short a field.
        request_fields = list(req)
        fail_uncovered_fields(field_coverage_errors(
            f"{cmd_info['domain']}.{cmd_info['name']}", "request", req,
            [f["name"] for f in request_fields]))
        for f in request_fields:
            t = RUST_TYPE_MAP.get(f["type"], "Value")
            serde_attr = f'#[serde(rename = "{f["json"]}")]'
            w(f"    {serde_attr}")
            if f.get("required", False):
                w(f"    pub {rust_ident(f['name'])}: {t},")
            else:
                w(f"    #[serde(default)]")
                w(f"    pub {rust_ident(f['name'])}: {t},")
        w("}")
        w()

    for cmd_info in commands:
        resp = cmd_info.get("response", [])
        if not resp:
            continue
        domain = cmd_info["domain"]
        name = cmd_info["name"]
        struct_name = f"{to_pascal(domain)}{to_pascal(name)}Response"
        w("#[derive(Debug, Clone, Serialize, Deserialize)]")
        w(f"pub struct {struct_name} {{")
        # The envelope leads every response struct — the keys the response
        # builder writes, in the order protocol.toml declares them, read from
        # that section rather than from a literal of this emitter's own, and
        # with the optionality its `appears` column gives them: a key every
        # reply carries (`status`) is written plain, one only some replies carry
        # (`cmd`, `queued` — the error replies have neither) as Option, so the
        # struct deserializes the replies the firmware really sends.
        for f in envelope_on_side(proto, "reply"):
            t = RUST_TYPE_MAP[f["type"]]
            if f["required"]:
                w(f"    pub {rust_ident(f['name'])}: {t},")
            else:
                w(f"    pub {rust_ident(f['name'])}: Option<{t}>,")
        # Each declared response field becomes an optional field of the struct —
        # every one of them, so the list is the declared array and the check
        # holds it there.
        response_fields = list(resp)
        fail_uncovered_fields(field_coverage_errors(
            f"{domain}.{name}", "response", resp,
            [f["name"] for f in response_fields]))
        for f in response_fields:
            t = RUST_TYPE_MAP.get(f["type"], "Value")
            serde_attr = f'#[serde(rename = "{f["json"]}")]'
            w(f"    {serde_attr}")
            w(f"    pub {rust_ident(f['name'])}: Option<{t}>,")
        w("}")
        w()

    result = "\n".join(lines)

    if out:
        out.write_text(result)
        print(f"  [rust] wrote {out}", file=sys.stderr)

    return result
