/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeMX / modified for RAM_D2 heap
 * @brief     System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the newlib libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found
 * in the LICENSE file in the root directory of this
 * software component. If no LICENSE file comes with this
 * software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <stdint.h>

/**
 * @brief _sbrk() allocates memory to the newlib heap and is
 *        used by malloc and others from the C library
 *
 * Heap is placed in RAM_D2 (0x30000000, 288KB) to preserve
 * DTCMRAM for performance-critical data. Bounded by linker
 * symbols _sram_d2_heap and _eram_d2_heap.
 *
 * @param incr Memory size
 * @return Pointer to allocated memory
 */
void *_sbrk(ptrdiff_t incr) {
  extern uint8_t _sram_d2_heap; /* Start of heap in RAM_D2, defined in linker script */
  extern uint8_t _eram_d2_heap; /* End of heap in RAM_D2, defined in linker script */
  static uint8_t *__sbrk_heap_end = NULL;
  uint8_t *prev_heap_end;

  /* Initialize heap end at first call */
  if (NULL == __sbrk_heap_end) {
    __sbrk_heap_end = &_sram_d2_heap;
  }

  prev_heap_end = __sbrk_heap_end;

  /* Protect heap from exceeding its reserved region */
  if (__sbrk_heap_end + incr > &_eram_d2_heap) {
    errno = ENOMEM;
    return (void *)-1;
  }

  __sbrk_heap_end += incr;

  return (void *)prev_heap_end;
}
