#!/usr/bin/env python3
"""
ThetaGP Protocol Code Generator

Reads protocol/protocol.toml and generates type-safe serialization code:
  - C++   header (protocol/proto.h)  — device side, ArduinoJson v7
  - Rust  module (protocol/proto.rs) — Tauri backend, serde
  - TS    types   (protocol/types.ts) — frontend

Usage:
  python3 scripts/gen_proto.py                       # all targets
  python3 scripts/gen_proto.py --target cpp           # C++ only
  python3 scripts/gen_proto.py --target rust           # Rust only
  python3 scripts/gen_proto.py --target ts             # TS only
  python3 scripts/gen_proto.py --dry-run               # print to stdout
  python3 scripts/gen_proto.py --protocol custom.toml  # custom path

Requires: Python 3.11+ (uses stdlib tomllib)
"""

import argparse
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Set

# ── Try tomllib (3.11+), fallback to tomli ──────────────────────────────────
try:
    import tomllib
except ImportError:
    try:
        import tomli as tomllib
    except ImportError:
        print("ERROR: Python 3.11+ (stdlib tomllib) or 'tomli' pip package required.",
              file=sys.stderr)
        sys.exit(1)


# ═════════════════════════════════════════════════════════════════════════════
# Type helpers
# ═════════════════════════════════════════════════════════════════════════════

CPP_TYPE_MAP = {
    "u8":     "uint8_t",
    "u16":    "uint16_t",
    "u32":    "uint32_t",
    "bool":   "bool",
    "string": "const char *",
    "any":    "JsonVariant",
}

RUST_TYPE_MAP = {
    "u8":     "u8",
    "u16":    "u16",
    "u32":    "u32",
    "bool":   "bool",
    "string": "String",
    "any":    "serde_json::Value",
}

TS_TYPE_MAP = {
    "u8":     "number",
    "u16":    "number",
    "u32":    "number",
    "bool":   "boolean",
    "string": "string",
    "any":    "any",
}


def to_pascal(name: str) -> str:
    """snake_case or SCREAMING_SNAKE → PascalCase"""
    return "".join(word.capitalize() for word in name.replace("-", "_").split("_"))


def to_snake(name: str) -> str:
    """PascalCase → snake_case (handles acronyms, does not modify SCREAMING_SNAKE)"""
    # If already snake_case (has underscores), return as-is
    if "_" in name:
        return name.lower()
    # Insert underscore before each uppercase letter that is:
    # - preceded by a lowercase letter (camelCase boundary)
    # - preceded by an uppercase and followed by lowercase (acronym tail)
    result = re.sub(r"(?<=[a-z])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])", "_", name)
    return result.lower()


def sanitize_cpp_comment(text: str) -> str:
    """Sanitize text for use in C++ // or /* */ comments."""
    return text.replace("*/", "* /").replace("\n", " ")


RUST_KEYWORDS = {
    "as", "break", "const", "continue", "crate", "else", "enum", "extern",
    "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod",
    "move", "mut", "pub", "ref", "return", "self", "Self", "static", "struct",
    "super", "trait", "true", "type", "union", "unsafe", "use", "where", "while",
    "abstract", "become", "box", "do", "final", "macro", "override", "priv",
    "try", "typeof", "unsized", "virtual", "yield",
}


def rust_ident(name: str) -> str:
    """Return a valid Rust identifier, escaping keywords with r#."""
    if name in RUST_KEYWORDS:
        return f"r#{name}"
    return name


# ═════════════════════════════════════════════════════════════════════════════
# TOML Loading
# ═════════════════════════════════════════════════════════════════════════════

def load_protocol(path: str) -> dict:
    with open(path, "rb") as f:
        return tomllib.load(f)


# ═════════════════════════════════════════════════════════════════════════════
# C++ Generator
# ═════════════════════════════════════════════════════════════════════════════

def gen_cpp(proto: dict, out: Optional[Path] = None) -> str:
    lines: List[str] = []
    types = proto.get("types", [])
    enums = proto.get("enums", [])
    commands = proto.get("commands", [])
    error_codes = proto.get("error_codes", {})

    # Build type name → fields lookup for nested serialization
    type_fields: Dict[str, list] = {t["name"]: t["fields"] for t in types}
    type_namespaces: Dict[str, str] = {t["name"]: t.get("namespace", "") for t in types}

    def w(line: str = "") -> None:
        lines.append(line)

    # ── Header ──────────────────────────────────────────────────────────────
    w("// =============================================================================")
    w("// Auto-generated by scripts/gen_proto.py — DO NOT EDIT MANUALLY")
    w("// Source: protocol/protocol.toml")
    w(f"// Generated: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    w("// =============================================================================")
    w("#pragma once")
    w("#include <ArduinoJson.h>")
    w("#include <cstdint>")
    w("#include <cstring>")
    w("#include <functional>")

    # Add includes for codebase-owned types
    for t in types:
        if not t.get("codebase_owned", False):
            continue
        ns = t.get("namespace", "")
        name = t["name"]
        if ns == "ThetaGP::Gamepad" and name == "GamepadRawInput":
            w("#include \"gamepad/gamepadstate.h\"")
        elif ns == "ThetaGP" and name == "HIDReport":
            w("#include \"drivers/gpdriver/hid/HIDDescriptors.h\"")

    w()

    # ── Error codes ──────────────────────────────────────────────────────────
    w("// =============================================================================")
    w("// Error Codes")
    w("// =============================================================================")
    w("namespace ThetaGP { namespace Proto {")
    w("enum class ErrorCode : uint8_t {")
    for name, info in error_codes.items():
        w(f"    {name} = {info['code']}, // {sanitize_cpp_comment(info['description'])}")
    w("};")
    w("}} // namespace ThetaGP::Proto")
    w()

    # ── Enums ────────────────────────────────────────────────────────────────
    for enum_info in enums:
        name = enum_info["name"]
        w(f"// ---------------------------------------------------------------------------")
        w(f"// {name} — {sanitize_cpp_comment(enum_info.get('description', ''))}")
        w(f"// ---------------------------------------------------------------------------")
        w(f"enum class {name} : uint8_t {{")
        for val in enum_info["values"]:
            desc = sanitize_cpp_comment(val.get("description", ""))
            w(f"    {val['name']} = {val['value']}, // {desc}")
        w("};")
        w()
        w(f"inline const char *{name}Name({name} v) {{")
        w(f"    switch (v) {{")
        for val in enum_info["values"]:
            w(f"        case {name}::{val['name']}: return \"{val['name']}\";")
        w(f"        default: return \"UNKNOWN\";")
        w(f"    }}")
        w(f"}}")
        w()

    # ── Enum converters ──────────────────────────────────────────────────────

    # ── Struct definitions ───────────────────────────────────────────────────
    for t in types:
        if t.get("codebase_owned", False):
            continue  # skip struct def; type exists in codebase
        name = t["name"]
        ns = t.get("namespace", "")
        desc = sanitize_cpp_comment(t.get("description", ""))
        w(f"// ---------------------------------------------------------------------------")
        w(f"// {desc}")
        w(f"// ---------------------------------------------------------------------------")
        # Open namespace
        if ns:
            ns_parts = ns.split("::")
            for part in ns_parts:
                w(f"namespace {part} {{")
        w(f"struct {name} {{")
        for f in t["fields"]:
            if f.get("omit_in_serialize"):
                # Still emit the field (used internally) but mark it
                pass
            cpp_type = CPP_TYPE_MAP.get(f["type"], f"/* unknown: {f['type']} */")
            desc = sanitize_cpp_comment(f.get("description", ""))
            default = ""
            if f["type"] in ("u8", "u16", "u32"):
                default_val = f.get("default", 0)
                if ns == "ThetaGP::Gamepad" and name == "GamepadRawInput":
                    mid_defaults = {"lx": "GAMEPAD_JOYSTICK_MID", "ly": "GAMEPAD_JOYSTICK_MID",
                                    "rx": "GAMEPAD_JOYSTICK_MID", "ry": "GAMEPAD_JOYSTICK_MID"}
                    if f["name"] in mid_defaults:
                        default = f"{{{mid_defaults[f['name']]}}}"
                    else:
                        default = f"{{{default_val}}}"
                else:
                    default = f"{{{default_val}}}"
            elif f["type"] == "bool":
                default = f"{{{str(f.get('default', 'false')).lower()}}}"
            elif f["type"] == "string":
                default = "{}"
            else:
                default = "{}"
            w(f"    {cpp_type} {f['name']}{default}; // {desc}")
        w("};")
        if ns:
            for _ in ns_parts:
                w("}")
        w()

    # ── Serialize helpers ────────────────────────────────────────────────────
    w("// =============================================================================")
    w("// Serialize helpers")
    w("// =============================================================================")
    w("namespace ThetaGP { namespace Proto {")

    # Add using declarations so bare names work in serializers
    for t in types:
        ns = t.get("namespace", "")
        name = t["name"]
        # HIDReport is a C-style typedef in global scope — no using needed
        if name == "HIDReport":
            continue
        if ns:
            w(f"using {ns}::{name};")

    w()

    for t in types:
        name = t["name"]
        ns = t.get("namespace", "")
        desc = sanitize_cpp_comment(t.get("description", ""))
        w(f"// Serialize {name} into a JsonObject")
        w(f"inline void serialize_{to_snake(name)}(JsonObject obj, const {name} &v) {{")
        for f in t["fields"]:
            if f.get("omit_in_serialize"):
                continue
            json_key = f["json"]
            field_name = f["name"]
            if json_key:
                w(f'    obj["{json_key}"] = v.{field_name};')
        w("}")
        w()

        # Deserialize
        w(f"// Deserialize {name} from a JsonDocument")
        w(f"inline void deserialize_{to_snake(name)}(const JsonDocument &doc, {name} &v) {{")
        for f in t["fields"]:
            if f.get("omit_in_serialize"):
                continue
            json_key = f["json"]
            field_name = f["name"]
            if not json_key:
                continue
            default_val = f.get("default", 0)
            # Map mid defaults for GamepadRawInput joystick
            if ns == "ThetaGP::Gamepad" and name == "GamepadRawInput":
                mid_defaults = {"lx": "GAMEPAD_JOYSTICK_MID", "ly": "GAMEPAD_JOYSTICK_MID",
                                "rx": "GAMEPAD_JOYSTICK_MID", "ry": "GAMEPAD_JOYSTICK_MID"}
                if field_name in mid_defaults:
                    w(f'    v.{field_name} = doc["{json_key}"] | {mid_defaults[field_name]};')
                    continue
            if f["type"] == "string":
                w(f'    v.{field_name} = doc["{json_key}"] | "";')
            elif f["type"] == "bool":
                w(f'    v.{field_name} = doc["{json_key}"] | false;')
            else:
                w(f'    v.{field_name} = doc["{json_key}"] | {default_val};')
        w("}")
        w()

    w("}} // namespace ThetaGP::Proto")
    w()

    # ── Command handling ────────────────────────────────────────────────────
    w("// =============================================================================")
    w("// Command dispatch table")
    w("// =============================================================================")
    w("namespace ThetaGP { namespace Proto {")
    w()
    w("// Command handler signature")
    w("using CommandHandler = void (*)(const char *cmd, JsonDocument &doc);")
    w()
    w("// Route table entry")
    w("struct CommandEntry {")
    w("    const char *name;")
    w("    CommandHandler handler;")
    w("};")
    w()
    w("// Forward declarations")
    for cmd_info in commands:
        domain = cmd_info["domain"]
        handler_name = f"handle_{domain}_{cmd_info['name']}"
        w(f"void {handler_name}(const char *cmd, JsonDocument &doc);")
    w()
    w("// Dispatch table")
    w("inline CommandEntry COMMAND_TABLE[] = {")
    for cmd_info in commands:
        domain = cmd_info["domain"]
        full_name = f"{domain}.{cmd_info['name']}"
        handler_name = f"handle_{domain}_{cmd_info['name']}"
        w(f'    {{"{full_name}", {handler_name}}},')
    w('    {nullptr, nullptr}  // sentinel')
    w("};")
    w()
    w("// Main dispatcher")
    w("inline void dispatch(const char *cmd, JsonDocument &doc) {")
    w("    for (const CommandEntry *e = COMMAND_TABLE; e->name; ++e) {")
    w("        if (strcmp(cmd, e->name) == 0) {")
    w("            e->handler(cmd, doc);")
    w("            return;")
    w("        }")
    w("    }")
    w("    // Unknown command — send error")
    w("    JsonDocument resp;")
    w('    resp["status"] = "error";')
    w('    resp["cmd"] = cmd;')
    w("    int queued = doc[\"queued\"].as<int>();")
    w("    resp[\"queued\"] = queued + 1;")
    w('    resp["error_code"] = 1;')
    w('    resp["reason"] = "unknown command";')
    w("}")
    w()
    w("}} // namespace ThetaGP::Proto")
    w()

    # ── Handler stubs ────────────────────────────────────────────────────────
    w("// =============================================================================")
    w("// Command handler implementations — EDIT these to add business logic")
    w("// =============================================================================")
    w("#ifdef __GNUC__")
    w("#pragma GCC diagnostic push")
    w('#pragma GCC diagnostic ignored "-Wunused-parameter"')
    w("#endif")
    w()

    for cmd_info in commands:
        domain = cmd_info["domain"]
        handler_name = f"handle_{domain}_{cmd_info['name']}"
        full_name = f"{domain}.{cmd_info['name']}"
        desc = sanitize_cpp_comment(cmd_info.get("description", ""))
        w(f"// ---------------------------------------------------------------------------")
        w(f"// {full_name} — {desc}")
        w(f"// ---------------------------------------------------------------------------")
        w(f"void {handler_name}(const char *cmd, JsonDocument &doc) {{")
        w(f"    // TODO: implement {handler_name}")
        w(f"    int queued = doc[\"queued\"].as<int>();")
        w(f"    JsonDocument resp;")
        w(f"    resp[\"status\"] = \"ok\";")
        w(f"    resp[\"cmd\"] = cmd;")
        w(f"    resp[\"queued\"] = queued + 1;")
        # Add response fields with defaults
        resp_fields = {}
        for rf in cmd_info.get("response", []):
            if rf.get("description"):
                w(f"    // resp[\"{rf['json']}\"] = ...; // {sanitize_cpp_comment(rf.get('description', ''))}")
        w(f"    // FrameLayer::getInstance().sendResponse(resp);")
        w(f"    (void)doc;")
        w("}")
        w()

    w("#ifdef __GNUC__")
    w("#pragma GCC diagnostic pop")
    w("#endif")
    w()

    result = "\n".join(lines)

    if out:
        out.write_text(result)
        print(f"  [cpp] wrote {out}", file=sys.stderr)

    return result


# ═════════════════════════════════════════════════════════════════════════════
# Rust Generator
# ═════════════════════════════════════════════════════════════════════════════

def gen_rust(proto: dict, out: Optional[Path] = None) -> str:
    lines: List[str] = []
    types = proto.get("types", [])
    enums = proto.get("enums", [])
    commands = proto.get("commands", [])
    error_codes = proto.get("error_codes", {})

    def w(line: str = "") -> None:
        lines.append(line)

    # ── Header ──────────────────────────────────────────────────────────────
    w("// =============================================================================")
    w("// Auto-generated by scripts/gen_proto.py — DO NOT EDIT MANUALLY")
    w("// Source: protocol/protocol.toml")
    w(f"// Generated: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    w("// =============================================================================")
    w()
    w("use serde::{Deserialize, Serialize};")
    w("use serde_json::Value;")
    w()

    # ── Error codes ──────────────────────────────────────────────────────────
    w("// ---------------------------------------------------------------------------")
    w("// Error Codes")
    w("// ---------------------------------------------------------------------------")
    w("#[derive(Debug, Clone, Copy, PartialEq, Eq)]")
    w("#[repr(u8)]")
    w("pub enum ErrorCode {")
    for name, info in error_codes.items():
        desc = sanitize_cpp_comment(info.get("description", ""))
        w(f"    /// {desc}")
        w(f"    {to_pascal(to_snake(name))} = {info['code']},")
    w("}")
    w()

    w("impl ErrorCode {")
    w("    pub fn from_u8(v: u8) -> Option<Self> {")
    w("        match v {")
    for name, info in error_codes.items():
        w(f"            {info['code']} => Some(Self::{to_pascal(to_snake(name))}),")
    w("            _ => None,")
    w("        }")
    w("    }")
    w("}")
    w()

    # ── Enums ────────────────────────────────────────────────────────────────
    for enum_info in enums:
        name = enum_info["name"]
        desc = sanitize_cpp_comment(enum_info.get("description", ""))
        w(f"/// {desc}")
        w("#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]")
        w("#[repr(u8)]")
        w(f"pub enum {name} {{")
        for val in enum_info["values"]:
            desc = sanitize_cpp_comment(val.get("description", ""))
            w(f"    /// {desc}")
            w(f"    #[serde(rename = \"{val['name'].lower()}\")]")
            w(f"    {to_pascal(val['name'].lower())} = {val['value']},")
        w("}")
        w()

    # ── Structs ──────────────────────────────────────────────────────────────
    for t in types:
        name = t["name"]
        desc = sanitize_cpp_comment(t.get("description", ""))
        w(f"/// {desc}")
        w("#[derive(Debug, Clone, Serialize, Deserialize)]")
        w(f"pub struct {name} {{")
        for f in t["fields"]:
            if f.get("omit_in_serialize"):
                rust_type = RUST_TYPE_MAP.get(f["type"], "Value")
            else:
                rust_type = RUST_TYPE_MAP.get(f["type"], "Value")
            desc = sanitize_cpp_comment(f.get("description", ""))
            serde_attr = f'#[serde(rename = "{f["json"]}")]'
            w(f"    /// {desc}")
            w(f"    {serde_attr}")
            w(f"    pub {rust_ident(f['name'])}: {rust_type},")
        w("}")
        w()

    # ── Command enum ─────────────────────────────────────────────────────────
    w("// ---------------------------------------------------------------------------")
    w("// Command types")
    w("// ---------------------------------------------------------------------------")
    w()

    # Generate request types for commands with request fields
    for cmd_info in commands:
        req = cmd_info.get("request", [])
        if not req:
            continue
        domain = cmd_info["domain"]
        name = cmd_info["name"]
        struct_name = f"{to_pascal(domain)}{to_pascal(name)}Request"
        w("#[derive(Debug, Clone, Serialize, Deserialize)]")
        w(f"pub struct {struct_name} {{")
        w('    pub cmd: String,')
        w('    pub queued: u32,')
        for f in req:
            t = RUST_TYPE_MAP.get(f["type"], "Value")
            serde_attr = f'#[serde(rename = "{f["json"]}")]'
            w(f"    {serde_attr}")
            if f.get("required", False):
                w(f"    pub {rust_ident(f['name'])}: {t},")
            else:
                w(f"    #[serde(default)]")
                w(f"    pub {rust_ident(f['name'])}: {t},")
        w("}")
        w()

    for cmd_info in commands:
        resp = cmd_info.get("response", [])
        if not resp:
            continue
        domain = cmd_info["domain"]
        name = cmd_info["name"]
        struct_name = f"{to_pascal(domain)}{to_pascal(name)}Response"
        w("#[derive(Debug, Clone, Serialize, Deserialize)]")
        w(f"pub struct {struct_name} {{")
        w('    pub status: String,')
        w('    pub cmd: String,')
        w('    pub queued: u32,')
        for f in resp:
            t = RUST_TYPE_MAP.get(f["type"], "Value")
            serde_attr = f'#[serde(rename = "{f["json"]}")]'
            w(f"    {serde_attr}")
            w(f"    pub {rust_ident(f['name'])}: Option<{t}>,")
        w("}")
        w()

    result = "\n".join(lines)

    if out:
        out.write_text(result)
        print(f"  [rust] wrote {out}", file=sys.stderr)

    return result


# ═════════════════════════════════════════════════════════════════════════════
# TypeScript Generator
# ═════════════════════════════════════════════════════════════════════════════

def gen_ts(proto: dict, out: Optional[Path] = None) -> str:
    lines: List[str] = []
    types = proto.get("types", [])
    enums = proto.get("enums", [])
    commands = proto.get("commands", [])
    error_codes = proto.get("error_codes", {})

    def w(line: str = "") -> None:
        lines.append(line)

    # ── Header ──────────────────────────────────────────────────────────────
    w("// =============================================================================")
    w("// Auto-generated by scripts/gen_proto.py — DO NOT EDIT MANUALLY")
    w("// Source: protocol/protocol.toml")
    w(f"// Generated: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    w("// =============================================================================")
    w()

    # ── Error codes ──────────────────────────────────────────────────────────
    w("// ---------------------------------------------------------------------------")
    w("// Error Codes")
    w("// ---------------------------------------------------------------------------")
    w("export const enum ErrorCode {")
    for name, info in error_codes.items():
        w(f"  {name} = {info['code']},")
    w("}")
    w()

    # ── Enums ────────────────────────────────────────────────────────────────
    for enum_info in enums:
        name = enum_info["name"]
        desc = sanitize_cpp_comment(enum_info.get("description", ""))
        w(f"// {desc}")
        w(f"export const enum {name} {{")
        for val in enum_info["values"]:
            desc = sanitize_cpp_comment(val.get("description", ""))
            w(f"  // {desc}")
            w(f"  {val['name']} = {val['value']},")
        w("}")
        w()

    # ── Interfaces ───────────────────────────────────────────────────────────
    for t in types:
        name = t["name"]
        desc = sanitize_cpp_comment(t.get("description", ""))
        w(f"// {desc}")
        w(f"export interface {name} {{")
        for f in t["fields"]:
            if f.get("omit_in_serialize"):
                continue
            ts_type = TS_TYPE_MAP.get(f["type"], "any")
            desc = sanitize_cpp_comment(f.get("description", ""))
            w(f"  // {desc}")
            w(f"  {f['json']}: {ts_type};")
        w("}")
        w()

    # ── Command request/response interfaces ─────────────────────────────────
    for cmd_info in commands:
        domain = cmd_info["domain"]
        name = cmd_info["name"]
        full_name = f"{domain}.{name}"
        desc = sanitize_cpp_comment(cmd_info.get("description", ""))

        # Request interface
        req = cmd_info.get("request", [])
        w(f"// {full_name} — Request ({desc})")
        if req:
            w(f"export interface {to_pascal(domain)}{to_pascal(name)}Request {{")
            w("  cmd: string;")
            w("  queued: number;")
            for f in req:
                ts_type = TS_TYPE_MAP.get(f["type"], "any")
                optional = "" if f.get("required", False) else "?"
                w(f"  {f['json']}{optional}: {ts_type};")
            w("}")
        else:
            w(f"export type {to_pascal(domain)}{to_pascal(name)}Request = {{ cmd: string; queued: number; }};")
        w()

        # Response interface
        BOILERPLATE_TS_RESPONSE_FIELDS = {"status", "cmd", "queued"}
        resp = cmd_info.get("response", [])
        if resp:
            w(f"export interface {to_pascal(domain)}{to_pascal(name)}Response {{")
            w("  status: string;")
            w("  cmd: string;")
            w("  queued: number;")
            for f in resp:
                if f["json"] in BOILERPLATE_TS_RESPONSE_FIELDS:
                    continue
                ts_type = TS_TYPE_MAP.get(f["type"], "any")
                w(f"  {f['json']}?: {ts_type};")
            w("}")
        else:
            # Generic response with status/cmd/queued
            pass
        w()

    result = "\n".join(lines)

    if out:
        out.write_text(result)
        print(f"  [ts]  wrote {out}", file=sys.stderr)

    return result


# ═════════════════════════════════════════════════════════════════════════════
# CLI
# ═════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description="ThetaGP Protocol Code Generator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python3 scripts/gen_proto.py
  python3 scripts/gen_proto.py --target cpp --dry-run
  python3 scripts/gen_proto.py --target rust,ts
        """,
    )
    parser.add_argument("--protocol", default="protocol/protocol.toml",
                        help="Path to protocol.toml (default: protocol/protocol.toml)")
    parser.add_argument("--target", default="cpp,rust,ts",
                        help="Comma-separated targets: cpp,rust,ts (default: all)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print generated code to stdout instead of writing files")
    parser.add_argument("--outdir-cpp", default="protocol",
                        help="Output dir for C++ generated header")
    parser.add_argument("--outdir-rust", default="protocol",
                        help="Output dir for Rust generated module")
    parser.add_argument("--outdir-ts", default="protocol",
                        help="Output dir for TS generated types")

    args = parser.parse_args()
    targets = [t.strip() for t in args.target.split(",")]
    proto_path = Path(args.protocol)

    if not proto_path.exists():
        print(f"ERROR: Protocol file not found: {proto_path}", file=sys.stderr)
        sys.exit(1)

    proto = load_protocol(str(proto_path))

    # Print summary
    types_list = proto.get("types", [])
    cmds_list = proto.get("commands", [])
    enums_list = proto.get("enums", [])
    print(f"ThetaGP Protocol Code Generator", file=sys.stderr)
    print(f"  Source:     {proto_path}", file=sys.stderr)
    print(f"  Types:      {len(types_list)}", file=sys.stderr)
    print(f"  Commands:   {len(cmds_list)}", file=sys.stderr)
    print(f"  Enums:      {len(enums_list)}", file=sys.stderr)
    print(f"  Targets:    {', '.join(targets)}", file=sys.stderr)
    print(file=sys.stderr)

    if args.dry_run:
        out_target = None
    else:
        out_target = object()  # truthy, but we use Path below

    for tgt in targets:
        if tgt == "cpp":
            out_file = None if args.dry_run else Path(args.outdir_cpp) / "proto.h"
            gen_cpp(proto, out_file)
            if args.dry_run:
                print(gen_cpp(proto))
        elif tgt == "rust":
            out_file = None if args.dry_run else Path(args.outdir_rust) / "proto.rs"
            gen_rust(proto, out_file)
            if args.dry_run:
                print(gen_rust(proto))
        elif tgt == "ts":
            out_file = None if args.dry_run else Path(args.outdir_ts) / "types.ts"
            gen_ts(proto, out_file)
            if args.dry_run:
                print(gen_ts(proto))
        else:
            print(f"WARNING: Unknown target '{tgt}' (supported: cpp, rust, ts)",
                  file=sys.stderr)

    print("Done.", file=sys.stderr)


if __name__ == "__main__":
    main()
