#!/usr/bin/env python3
"""
ThetaGP Language Server Configuration Generator

Asks the C++ compiler for its system include search list and writes it to
.clangd. The list depends on the toolchain and its multilib selection, so it is
read from the compiler rather than kept by hand.
"""

import argparse
import os
import subprocess
import sys

SEARCH_START = "#include <...> search starts here:"
SEARCH_END = "End of search list."


def probe_includes(compiler: str, flags: list[str]) -> list[str]:
    """Return the compiler's system include directories in search order."""
    result = subprocess.run(
        [compiler, *flags, "-E", "-v", "-x", "c++", os.devnull],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(
            f"[ERROR] {compiler} failed to report its include search list",
            file=sys.stderr,
        )
        print(result.stderr, file=sys.stderr)
        sys.exit(1)

    paths: list[str] = []
    inside = False
    for line in result.stderr.splitlines():
        if line.strip() == SEARCH_START:
            inside = True
            continue
        if line.strip() == SEARCH_END:
            break
        if inside and line.startswith(" "):
            paths.append(line.strip())

    if not paths:
        print(
            f"[ERROR] no include directories reported by {compiler}",
            file=sys.stderr,
        )
        sys.exit(1)
    return paths


def render_clangd(includes: list[str]) -> str:
    body = "\n".join(f"    - -isystem{path}" for path in includes)
    return (
        "# Generated by scripts/generate_clangd.py from the toolchain.\n"
        "# Carries the compiler's include search list: the compilation database\n"
        "# holds the project's own -I paths but not the toolchain's, so the\n"
        "# language server reads them from here.\n"
        "CompileFlags:\n"
        "  Add:\n"
        f"{body}\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--compiler", required=True, help="C++ compiler to probe")
    parser.add_argument(
        "--flags",
        default="",
        help="space-separated target flags (mcpu, mthumb, mfpu, mfloat-abi)",
    )
    parser.add_argument("--out", required=True, help="path to the .clangd file")
    args = parser.parse_args()

    includes = probe_includes(args.compiler, args.flags.split())
    print(
        f"[INFO] {args.compiler}: {len(includes)} include directories",
        file=sys.stderr,
    )
    print(f"[INFO] Writing {args.out} ...", file=sys.stderr)
    with open(args.out, "w") as f:
        f.write(render_clangd(includes))
    print("[INFO] Language server configuration generated", file=sys.stderr)


if __name__ == "__main__":
    main()
