[board_info]
identifier     = "BoringTechH743"
name           = "BoringTechH743"
mcu            = "STM32H743xx"
mcu_series     = "STM32H7"

[led0]
pin        = "PC0"
active_low = true

[keypad]
drive_mode  = "scan_matrix"
active_mode = "low"

drive_pins = ["PD8", "PD9"]
sense_pins = ["PC4", "PC5"]

key_map = [
    [0, 1],
    [2, 3],
]

button_map = [
    [0, "B1"],
    [1, "B2"],
    [2, "B3"],
    [3, "B4"],
]

[usb]
hw_periph = "USB2"
speed     = "full_speed"

[[bus.uart]]
bind       = "logger"
peripheral = "UART1"
tx         = "PA9"
rx         = "PA10"

[[bus.spi]]
bind       = "flash"
peripheral = "SPI2"
sclk       = "PB13"
mosi       = "PB15"
miso       = "PB14"
ncs        = "PB12"

[flash]
chip = "w25qxx"